// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/king19800105/feigo/api/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	SMSSendEndpoint  endpoint.Endpoint
	SMSQueryEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.ApiService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		SMSQueryEndpoint: MakeSMSQueryEndpoint(s),
		SMSSendEndpoint:  MakeSMSSendEndpoint(s),
	}
	for _, m := range mdw["SMSSend"] {
		eps.SMSSendEndpoint = m(eps.SMSSendEndpoint)
	}
	for _, m := range mdw["SMSQuery"] {
		eps.SMSQueryEndpoint = m(eps.SMSQueryEndpoint)
	}
	return eps
}
