// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/king19800105/feigo/sms/pkg/endpoint"
	pb "github.com/king19800105/feigo/sms/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	send grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.SmsServer {
	return &grpcServer{send: makeSendHandler(endpoints, options["Send"])}
}
