// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	"github.com/go-kit/kit/transport/http"
	"github.com/gorilla/mux"
	"github.com/king19800105/feigo/api/pkg/endpoint"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	// 设置组路径名称
	m = m.PathPrefix("/api").Subrouter()
	makeSMSSendHandler(m, endpoints, options["SMSSend"])
	makeSMSQueryHandler(m, endpoints, options["SMSQuery"])
	return m
}
